### ISSUE TITLE
1/7/24_TESTER learn to error log

### ISSUE THREAD

**Issue by quocdung2603** [ducbv10/MockProject_062024_Nhom4#17]
Xem kỹ 2 bài giảng này để sau này bắt chước làm theo:
     Link bài giảng về hd cách log lỗi: https://docs.google.com/document/d/e/2PACX-1vQKwGmhvN9z7nuiS_Nh5ukmEFLHhlUe74d9p4-EL8vBKsNjCE0uiaUlZp--AdJuje7Eu0eO-g5QBgEv/pub
     Link HuongDanCachLogBugBangGITHUB: https://docs.google.com/document/d/e/2PACX-1vQ5ILaOATxEAAAhHOcgjeI9sJOfjexdI_KVPkJEx_DAPQ4K2ni_cibboBWIIx1UzxqNwqH-d9_6aZCr/pub
   Đây là 2 bài giảng nằm trong khóa đào tạo tester của trung tâm Việt Trí Đạo.
   Trong lúc xem 2 bài giảng ở trên thì có cần tham khảo đến file [MockProject_Defect List Sample.xlsx] nha mọi người.
  
Deadline: 20h00 today

**Comment by lambui21** [comment]
done

**Comment by nguyenquynhnhupl** [comment]
Done

**Comment by chloenth** [comment]
done
