### ISSUE TITLE
3/7/24_Learn how to test Web Interfaces using Responsive techniques

### ISSUE THREAD

**Issue by quocdung2603** [ducbv10/MockProject_062024_Nhom4#28]
Refer to the following links:
     https://idesign.vn/graphic-design/su-khac-nhau-giua-thiet-ke-web-adaptive-va-responsive-438967.html
     https://bizmac.com/blog/tin-cong-nghe/su-khac-biet-giua-adaptive-design-va-responsive-design.html
     https://viblo.asia/p/test-responsive-web-design-nhu-the-nao-OeVKBgkMZkW

Do the exercise: Find errors when testing responsive web for the following website:
     https://www.gdt.gov.vn/wps/portal
Note: Use Chrome browser to test, with the help of DevTools using the F12 key in Chrome, see the following link for how to use:
     https://viblo.asia/p/test-responsive-va-device-specific-viewports-tren-devtools-f12-cua-browser-phan-1-XL6lAvgB5ek

**Comment by lambui21** [comment]
dône

**Comment by nguyenquynhnhupl** [comment]
Done

**Comment by chloenth** [comment]
Done

**Comment by nguyenquynhnhupl** [comment]
Done

**Comment by thanhtin102** [comment]
done
