### ISSUE TITLE
Review SQL

### ISSUE THREAD

**Issue by tranducphat204** [ducbv10/MockProject_062024_Nhom4#8]
[Java Coding Convention.xls](https://github.com/user-attachments/files/16007004/Java.Coding.Convention.xls)
[SQLCoBan_DB_NghiepVu_1.xlsx](https://github.com/user-attachments/files/16007005/SQLCoBan_DB_NghiepVu_1.xlsx)

**Comment by Thu20722** [comment]
☑️

**Comment by chloenth** [comment]
☑️

**Comment by ducbv10** [comment]
☑️

**Comment by nguyenquynhnhupl** [comment]
****

**Comment by lambui21** [comment]
☑️
